# Generated by Django 3.2 on 2021-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bhyhospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=40)),
                ('himage', models.ImageField(default='', upload_to='byimgs')),
                ('haddr', models.CharField(default='', max_length=100)),
                ('hphone', models.CharField(default='', max_length=100)),
                ('hmap', models.CharField(default='', max_length=50)),
                ('hlink', models.CharField(default='', max_length=50)),
                ('hcordinate', models.CharField(default='', max_length=50)),
                ('hdis', models.FloatField(blank=True, null=True)),
                ('htiming', models.CharField(default='', max_length=100)),
                ('hclosed', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vaccinename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.FloatField(blank=True, default='', null=True)),
                ('vyear1', models.CharField(max_length=40)),
                ('vname', models.CharField(max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name='vasaihospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=40)),
                ('himage', models.ImageField(default='', upload_to='byimgs')),
                ('haddr', models.CharField(default='', max_length=100)),
                ('hphone', models.CharField(default='', max_length=100)),
                ('hmap', models.CharField(default='', max_length=50)),
                ('hcordinate', models.CharField(default='', max_length=50)),
                ('hdis', models.FloatField(blank=True, null=True)),
                ('hlink', models.CharField(default='', max_length=50)),
                ('htiming', models.CharField(default='', max_length=100)),
                ('hclosed', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
