# Generated by Django 3.2 on 2021-05-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage', '0003_auto_20210510_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmain',
            name='haddr',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vmain',
            name='hlink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vmain',
            name='hmap',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vmain',
            name='hname',
            field=models.CharField(max_length=500),
        ),
    ]
