# Generated by Django 3.2 on 2021-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage', '0004_auto_20210512_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='noti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=500)),
                ('date', models.CharField(default='', max_length=500)),
                ('time', models.CharField(default='', max_length=500)),
                ('hname', models.CharField(default='', max_length=500)),
                ('vname', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
